### ISSUE TITLE
Hunspell dictionaries not found (fixed)

### ISSUE THREAD

**Issue by nisaea** [jacquetc/plume-creator-legacy#2]
I'm on Fedora and the dictionaries are not in "/usr/share/hunspell/" so I changed l.282 of spellchecker.cpp accordingly, and I thought you might want to know it and add "/usr/share/myspell/" to the list of paths to look into when running Linux. :)

**Comment by jacquetc** [comment]
Hello Nisaea, 

Thank you, I'll add the line tonight.

Cordialement,
Cyril Jacquet

**Comment by nisaea** [comment]
Thanks a lot! ^^
