### ISSUE TITLE
Can you explain how to compile this program?

### ISSUE THREAD

**Issue by mke21** [jacquetc/plume-creator-legacy#3]
I am not using Ubuntu or Debian or the like, so I cannot use .deb files. I would like to use this program. I tried the newer python version, but it is very unstable and actually unusable (b.t.w. will that be developed further? Last commit was quite a while ago). So for now I would like to run the legacy version. However, I have no idea how to compile and install the program. I've cloned this repository so I have the latest code.
The INSTALL_NOTES are not very clear to me.

**Comment by jacquetc** [comment]
Hello Mike,
 
Yes the python version is unusable for now, but you can find recent commits in the straighten-data-api branch. 

As far as I remember,to compile the old Plume, you only have to install Qt packages (or install Qt SDK),
g++
make
qmake
libqt4-dev
libzip-dev
libhunspell-dev


 then type "qmake" , "make" , "make install"

Regards,
Cyril Jacquet

**Comment by mke21** [comment]
Thanks. Still does not work though, I get all sorts of errors and don't get a binary. (I type "qmake *.cpp in the src directory). Sorry, I'm not very good at c++ and compiling I'm afraid.
Awesome that you are still working on the python version. I believe it will make distribution much simpler. Especially since I know Python a lot better :)

**Comment by jacquetc** [comment]
qmake plume-creator.pro
make
sudo make install

It will be an hybrid c++/python since I'm so much at ease with c++
