### ISSUE TITLE
Crashing when opening file

### ISSUE THREAD

**Issue by abergmot** [jacquetc/plume-creator-legacy#7]
On debian Stretch, plume-creator is version 0.66+dfsg1-3.1+b2 when I'm trying to open a *.plume file made on another computer running the same version, but on Ubuntu 16+ (can't get the version now), Plume (already opened) crashes. In the terminal I get "Exception en point flottant." ("Floating point exception" I guess in english...

I can still open the *.plume file on Ubuntu.
The size of the file is 189 822 o

**Comment by jacquetc** [comment]
*.plume files are .zip files. You can verify if the content corrupt or not. I don't remember, but maybe there is an upgrade of the .plume file when opening it in a newer Plume, then the file is inoperable on an older Plume. I can only guess from afar.
